/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"icon-music" | "icon-oi-logo" | "icon-playing">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"icon-music" | "icon-oi-logo" | "icon-playing">;
          default: string;
          required: true;
      };
  }>>, {
      name: "icon-music" | "icon-oi-logo" | "icon-playing";
  }>;
  export const svgNames: ["icon-music", "icon-oi-logo", "icon-playing"];
  export type SvgName = "icon-music" | "icon-oi-logo" | "icon-playing";
  export default SvgIcon;
}
