/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/[...all]',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/playlist/': RouteRecordInfo<
      '/playlist/',
      '/playlist',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/podcast/': RouteRecordInfo<
      '/podcast/',
      '/podcast',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recommend/': RouteRecordInfo<
      '/recommend/',
      '/recommend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting': RouteRecordInfo<
      '/setting',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/playlist/index.vue': {
      routes:
        | '/playlist/'
      views:
        | never
    }
    'src/pages/podcast/index.vue': {
      routes:
        | '/podcast/'
      views:
        | never
    }
    'src/pages/recommend/index.vue': {
      routes:
        | '/recommend/'
      views:
        | never
    }
    'src/pages/search/index.vue': {
      routes:
        | '/search/'
      views:
        | never
    }
    'src/pages/setting.vue': {
      routes:
        | '/setting'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
